name: Pass or fail

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  always_fail:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Always fail
      run: |
        exit 1
    - name: Test with pytest
      run: |
        pytest